# Load Service part of template
---
apiVersion: v1
kind: Service
metadata:
  name: {{ template "solace.fullname" . }}
  labels:
    heritage: {{ .Release.Service }}
    release: {{ .Release.Name }}
    chart: {{ .Chart.Name }}-{{ .Chart.Version }}
    app: {{ template "solace.name" . }}

{{- if eq .Values.cloudProvider  "aws" }}
{{- else if eq .Values.cloudProvider "gcp" }}
 {{- if .Values.service.internal }}
  annotations:
    cloud.google.com/load-balancer-type: "internal"
 {{- end }} #end internal
{{- end }} #end gcp
spec:
  type: {{.Values.service.type}}
  ports:{{ range $item := .Values.service.externalPort }}
  - port: {{ $item.port }}
    protocol: {{ $item.protocol }}
    name: {{ $item.name }}{{end}}
  selector:
    app: {{ template "solace.name" . }}
    release: {{ .Release.Name }}
    active: "true"