# Default storage, exemplifies simplisity, will create a /mnt/stateful_partition dir on host 
#  and use this for Solace message spool 
solace:
  redundancy: false
  size: small
# Current options are [gcp|aws|azure]
cloudProvider: SOLOS_CLOUD_PROVIDER
image:
  repository: SOLOS_IMAGE_REPO
  tag: SOLOS_IMAGE_TAG
  pullPolicy: IfNotPresent
filepaths:
  configmap: "/mnt/disks/solace"
  secrets: "/mnt/disks/secrets"
service:
  internal: false
  type: LoadBalancer
  externalPort:
    - port: 22
      protocol: TCP
      name: ssh
    - port: 1883
      protocol: TCP
      name: mqtt
    - port: 5672
      protocol: TCP
      name: amqp
    - port: 8000
      protocol: TCP
      name: mqttws     
    - port: 8080
      protocol: TCP
      name: semp
    - port: 9000
      protocol: TCP
      name: rest
    - port: 55003
      protocol: TCP
      name: smfc
    - port: 55555
      protocol: TCP
      name: smf
  internalPort:
    - port: 80
      protocol: TCP
    - port: 8080
      protocol: TCP
    - port: 443
      protocol: TCP
    - port: 8443
      protocol: TCP
    - port: 55555
      protocol: TCP
    - port: 22
      protocol: TCP
storage:
  persistent: false
