apiVersion: v1
description: A Helm chart for Kubernetes
name: solace-kubernetes
version: 0.1.0
icon: https://dev.solace.com/wp-content/uploads/2016/10/solace-logo-white.png
maintainers:
  - name: kenbarr
    email: ken.barr@solace.com
sources:
   - http://dev.solace.com
keywords:
- solace
- vmr